{
 "title": "Nest Thermostat",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nest_ambient_temperature_celsius",
     "legendFormat": "Inside"
    },
    {
     "expr": "nest_weather_temperature_celsius",
     "legendFormat": "Outside"
    },
    {
     "expr": "nest_setpoint_temperature_celsius",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Humidity and Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "nest_humidity_percent", "legendFormat": "Inside Humidity" },
    { "expr": "nest_weather_humidity_percent", "legendFormat": "Outside Humidity" },
    {
     "expr": "nest_weather_pressure_hectopascal",
     "legendFormat": "Outside Pressure"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nest_ambient_temperature_celsius",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 16 },
   "targets": [
    { "expr": "nest_heating", "legendFormat": "Heating On" }
   ]
  }
 ]
}